### ISSUE TITLE
no run

### ISSUE THREAD

**Issue by witchanto** [HubbleCommand/run#1]
I have visual studio code and your run Hubble command, 
but he said: 
A01.pas] compiling... error!
/bin/sh: fpc: command not found

if I need fpc, which I can not install on Mac 15, 
for what is your thing?

**Comment by HubbleCommand** [comment]
You should be able to use [fpc](https://formulae.brew.sh/formula/fpc) on a mac, given that Lazarus has a mac version that depends on fpc [(*)](https://sourceforge.net/projects/lazarus/files/Lazarus%20macOS%20x86-64/Lazarus%203.6/).

When using the run option, all this extension does is open the file with the system-preferred app. If you're on mac, you can change it by following [this](https://support.apple.com/en-gb/guide/mac-help/mh35597/mac). You'll need to make sure the app is configured correctly, and in your case that your code compiles. If it's trying to open it with fpc, but fpc isn't in your vars or whatever mac uses en lieu of environment variables and Path, then this won't work and you'll have to configure it, or set a different default app.

I don't know what else you're doing, but if you have multiple steps with compiling and whatnot, I'd recommend using [VSCode's built-in task system](https://code.visualstudio.com/docs/editor/tasks) *if you can* (there have been times where the task system isn't flexible enough). There's a partial example for pascal [in this other extension where you opened an issue](https://github.com/alefragnani/vscode-language-pascal?tab=readme-ov-file#task-build).

**Comment by witchanto** [comment]
1 reason i can not use fpc is, because mac do not run the dmg, because he do not know if it harms as virus. 
and your explaination targets on fragnani's task build, so do i need your extension additional?
and if i use fpc, so for what i need your run or VSC?

**Comment by HubbleCommand** [comment]
- "mac do not run the dmg, because he do not know if it harms as virus" -> you can still install it, just make sure you trust the source. Regardless, you can [install it with homebrew](https://formulae.brew.sh/formula/fpc).
- "so do i need your extension additional" -> no
- "if i use fpc, so for what i need your run or VSC" -> FPC is just the compiler, if you want an editor you can use VSCode, Lazarus, Delphi, or whatever
